bases:
- ../../peraccount

nameSuffix: '-08'

patches:
  - path: load-generator-08.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: load-generator
      namespace: scalyr-loadgen      


