apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: purpose
                    operator: In
                    values:
                      - general
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: load-generator
              topologyKey: kubernetes.io/hostname
      containers:
      - name: scalyr-agent
        env:
          - name: SCALYR_API_KEY
            valueFrom:
              secretKeyRef:
                name: loadgen-api-keys
                key: load-generator-06-write-logs-key
