bases:
- ../../peraccount

nameSuffix: '-01'

patches:
  - path: load-generator-01.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: load-generator
      namespace: scalyr-loadgen

