bases:
- ../../peraccount

nameSuffix: '-02'

patches:
  - path: load-generator-02.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: load-generator
      namespace: scalyr-loadgen

