resources:
- scalyr-loadgen.yaml
- scalyr-service-account.yaml
- loadgen-telemetry-configmap.yaml
- load-generator-configmap.yaml
- loadgen-telemetry-daemonset.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- literals:
  - telemetry-write-logs-key=override_me
  - load-generator-write-logs-key=override_me
  name: loadgen-api-keys
  namespace: scalyr-loadgen
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
