apiVersion: v1
kind: ConfigMap
data:
  SCALYR_K8S_CLUSTER_NAME: loadgen-telemetry-cluster
  #
  # EU customers must uncomment this next line:
  # SCALYR_SERVER: "https://upload.eu.scalyr.com"
metadata:
  name: loadgen-telemetry-configmap
  namespace: scalyr-loadgen
